---
language: ruby
bundler_args: --without development
before_install: rm Gemfile.lock || true
rvm:
  - 1.9.3
  - 2.0.0
script: bundle exec rake test
env:
  - PUPPET_VERSION="~> 3.7"
  - PUPPET_VERSION="~> 4.0"
